db:
  dsn: "root:root@tcp(127.0.0.1:3308)/tinybook?charset=utf8mb4&parseTime=True&loc=Local"
redis:
  addr: "localhost:30001"
mongodb:
  ip: "localhost"
  port: "30003"
  username: "root"
  password: "123456"
  dbname: "tinybook"
  authSource: "admin"
kafka:
  brokers: "localhost:9092"