apiVersion: apps/v1
kind: Deployment
metadata:
  name: tinybook-service
spec:
  # 以下配置为服务副本数 2个
  replicas: 2
  selector:
    matchLabels:
      app: tinybook-service
  template:
    metadata:
      labels:
        app: tinybook-service
    spec:
      # 以下配置表示:
      # 服务容器的镜像为ycvk/tinybook:v0.0.1，镜像中的容器端口为8081，容器资源限制为0.5核CPU和128Mi内存
      containers:
        - name: tinybook
          image: ycvk/tinybook:v0.0.1
          env:
            - name: TZ
              value: Asia/Shanghai
          ports:
            - containerPort: 8081
          resources:
            limits:
              cpu: "0.5"
              memory: 128Mi
            requests:
              cpu: "0.5"
              memory: 128Mi


